eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true      # This service should register itself
    fetch-registry: true            # This service should fetch the registry for discovery
    service-url:
      defaultZone: http://localhost:8761/eureka/   # URL of the Eureka server

